apiVersion: v1
kind: Secret
metadata:
  name: fence-agents-credentials-hpe-ilo
  namespace: openshift-workload-availability
  labels:
    app.kubernetes.io/name: fence-agents-remediation
    app.kubernetes.io/component: instance
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
stringData:
  username: CHANGE_ME_ILO_USER
  password: CHANGE_ME_ILO_PASSWORD
