apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fence-agents-remediation-template.yaml
  - node-health-check.yaml
  - kube-descheduler.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ocpvirt-workloads-ha
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
