apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-node-maintenance-operator.yaml
  - 02-fence-agents-remediation-operator.yaml
  - 03-node-health-check-operator.yaml
  - 04-kube-descheduler-operator.yaml
